services:
  samba:
    image: samba-aapl
    container_name: samba-server
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - "./mount_script:/mount_script"
      - "./logs:/app/logs"
      - "./user.conf:/app/user.conf"
    ports:
      - "139:139"
      - "445:445"
